# Generated by Django 3.2.5 on 2021-07-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fd', models.IntegerField(blank=True, null=True)),
                ('mf', models.IntegerField(blank=True, null=True)),
                ('stocks', models.IntegerField(blank=True, null=True)),
                ('real_estate', models.IntegerField(blank=True, null=True)),
                ('gold', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.employee')),
            ],
            options={
                'db_table': 'investments',
            },
        ),
        migrations.CreateModel(
            name='Incomemanagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings', models.IntegerField(blank=True, null=True)),
                ('investments', models.IntegerField(blank=True, null=True)),
                ('growth_rate', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.employee')),
            ],
            options={
                'db_table': 'income_management',
            },
        ),
    ]
