# Generated by Django 3.2.5 on 2021-07-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_incomemanagement_investments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemanagement',
            name='emp_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.employee'),
        ),
    ]
