# Generated by Django 3.2.5 on 2021-07-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_incomemanagement_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='emp_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.employee'),
        ),
    ]
